function createfigure_SMES(Y1)
%CREATEFIGURE2(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Jul-2015 15:28:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'93','83','73','63','53','43','33','23','13','3'},...
    'XTick',[0 10 20 30 40 50 60 70 80 90],...
    'FontSize',26);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('$\hat{e}$','FontSize',48,'Interpreter','latex');

% Create xlabel
xlabel('Number of Components','FontSize',28.6);

% Create plot
plot(Y1,'LineWidth',3);

