function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Jun-2015 15:09:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Consumption TIme [s]','FontSize',22);

% Create xlabel
xlabel('Number of the GMM components ','FontSize',22);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3);
set(plot1(1),'DisplayName','Convex Optimization','Color',[0 0 1]);
set(plot1(2),'DisplayName','Expectation Maximization','Color',[1 0 0]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',18);

